export const permittedSystemEntites = [
    'mystem.geo',
    'mystem.persn',
    'mystem.obsc',
    'mystem.patrn',
    'mystem.famn',
    'pymorphy.romn',
    'pymorphy.latn',
    'pymorphy.numb',
    'pymorphy.intg',
    'pymorphy.abbr',
    'pymorphy.name',
    'pymorphy.surn',
    'pymorphy.patr',
    'pymorphy.geox',
    'pymorphy.orgn',
    'duckling.number',
    'duckling.ordinal',
    'duckling.amount-of-money',
    'duckling.distance',
    'duckling.time',
    'duckling.date',
    'duckling.time-of-day',
    'duckling.duration',
    'duckling.phone-number',
    'duckling.email',
    'duckling.url',
    'mlps-obscene.obscene',
    'zb.datetime',
    'zb.number',
] as const;

export type PermittedSystemEntitiesType = Array<typeof permittedSystemEntites[number]>;
